name: Notify IFTTT on PR to Original Repo

on:
  pull_request:
    types: [opened, reopened]

jobs:
  notify-ifttt:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.base.repo.full_name == 'ICE-graduation-project/front-end' }}

    steps:
    - name: Send notification to IFTTT
      run: |
        curl -X POST https://maker.ifttt.com/trigger/github_pr/with/key/cikJxT4rr-GhQ2gp56ZfCH \
        -H "Content-Type: application/json" \
        -d '{"value1": "${{ github.repository }}", "value2": "${{ github.event.pull_request.html_url }}", "value3": "${{ github.event.pull_request.title }}"}'
