name: Notify IFTTT on PR

on:
  pull_request:
    types:
      - opened

jobs:
  run_if:
    if:  startsWith(github.head_ref, 'ICE-graduation-project/')
    runs-on: ubuntu-latest
    steps:
      - run: echo "으아악"
