name: PR Notification

on:
  pull_request:
    types: [opened]

jobs:
  notify:
    if: github.event.pull_request.user.login == 'pakxe' && github.event.repository.full_name == 'ICE-graduation-project/front-end'
    runs-on: ubuntu-latest
    steps:
    - name: Send notification to IFTTT
      run: |
        curl -X POST -H "Content-Type: application/json" -d '{"value1":"${{ github.event.pull_request.html_url }}"}' https://maker.ifttt.com/trigger/github_pr/with/key/cikJxT4rr-GhQ2gp56ZfCH
